services:
  - type: web
    name: family-live
    runtime: node
    repo: https://github.com/familylive/family-live
    plan: free
    region: frankfurt
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_lU5kMRCmKSP6@ep-autumn-hill-axbd5hw6.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
  - type: web
    name: live-24
    runtime: node
    repo: https://github.com/familylive/family-live
    rootDir: livestar
    plan: free
    region: frankfurt
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    healthCheckPath: /

    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_lU5kMRCmKSP6@ep-autumn-hill-axbd5hw6.c-4.us-east-2.aws.neon.tech/livestar?sslmode=require